# Generated by Django 3.2.5 on 2021-09-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('pk_sites', models.AutoField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=264, unique=True)),
                ('site_url', models.URLField(unique=True)),
                ('site_webhook', models.URLField(unique=True)),
                ('site_status', models.BooleanField()),
                ('slack_account_url', models.URLField()),
            ],
        ),
    ]
