# Generated by Django 3.2.5 on 2021-09-23 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sites',
            new_name='Website',
        ),
        migrations.RenameField(
            model_name='website',
            old_name='pk_sites',
            new_name='pk_website',
        ),
    ]
