# Generated by Django 3.2.5 on 2021-09-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20210924_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='site_status',
        ),
        migrations.AddField(
            model_name='website',
            name='site_up_status',
            field=models.BooleanField(default=False),
        ),
    ]
