# Generated by Django 3.2.5 on 2021-09-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20210924_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='slack_channel',
            field=models.CharField(default='', max_length=264),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='slack_token',
            field=models.CharField(default='', max_length=264),
            preserve_default=False,
        ),
    ]
