# Generated by Django 3.2.5 on 2021-09-26 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auto_20210926_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='slack_account_url',
        ),
    ]
